### ISSUE TITLE
Links in README.md are broken

### ISSUE THREAD

**Issue by UweBlock** [hadley/staticdocs#104]
As of today, 2016-07-31, two of the links in README.md are broken:

1. http://staticdocs.had.co.nz/dev/ address could not be found
2. http://www.inside-r.org/ is redirected to [MRAN](https://mran.microsoft.com/)

**Comment by jranke** [comment]
@hadley Is the staticdocs meta site permanently gone or do you plan to resurrect it? I just built the static docs of staticdocs for the current master branch using the current master branch and it was building fine, so is it just a matter of finding the right web space for this?

@UweBlock http://www.inside-r-.org is now redirected to bing... But the complete paragraph is not true any more, as we do not have rendered help pages on inside-r.org any more (they were outdated since a long time ago). Is anyone aware of an alternative for HTML rendered help pages of all CRAN packages?

**Comment by hadley** [comment]
Staticdocs is dead for now, but will probably bring back to life in next 6-12 months. Need to rethink in context of rmarkdown websites.
