### ISSUE TITLE
build_reference 

### ISSUE THREAD

**Issue by hadley** [hadley/staticdocs#130]
Use if you just want the reference pages, not the complete site.

**Comment by bborgesr** [comment]
Yes! As is right now, this version of staticdocs breaks our Shiny website: it overwrites our landing page (reference/shiny/latest) to have the contents of the README, and generates a new reference.html (in our case at reference/shiny/latest/reference.html). 

I'm happy to try to work around this if this is immutable from your side, but I think it would make sense to allow people to say `with_README = FALSE` as before. It seems you were thinking of doing a different function `build_reference` to be used instead of `build_site`. But, people may want more than just the reference: demos, vignettes, and, in our case, NEWS.

So, imo, I think the best thing would be to either:

1. make each of these things (README, reference, examples, NEWS, vignettes, demos) a boolean arg to `build_site` (`with_vignettes`, `with_reference`, `with_examples`, etc).

2. make each of these things a separate function, and people call just the functions they need (ex, in our case, this would probably be: `build_reference(), build_news()`). In this case, `build_site` could still exist, but it would always build everything (?)

I like the first one better, but can't really say why. Maybe it's because it seems neater (so unnecessary duplication of arguments). If you want, I can work on this and submit a PR.

**Comment by hadley** [comment]
I think I'd prefer a new function (or lots of smaller exported functions) to give people get finer control. Shiny is a special case because it has much more content than the typical package website.

**Comment by bborgesr** [comment]
As I think more about it, lots of smaller exported functions is actually probably the best way to go. Even for shiny, since we'd like to set the path for the reference page and for the NEWS page in different places, and independent from one another. So it would make sense to have those be two separate functions. When I was working in the NEWS PR, I had that dilemma, because I wanted "news" to be able to be either a subset of the main directory *or* a different directory altogether. My solution (which was to include a `news_path` as yet another argument to `build_site`) isn't at all elegant...

So, I'm definitely changing my mind to lots of smaller functions, it makes a lot more sense conceptually. So excited about all of these new features!

**Comment by hadley** [comment]
Teased apart in my local version which I'll push shortly
